"""Remove legacy appointment tables

Revision ID: 23adc9a02d5f
Revises: 5e4009c5bb32
Create Date: 2026-09-22 23:50:18.376208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23adc9a02d5f'
down_revision = '5e4009c5bb32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appointment')
    op.drop_table('client')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appointment',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('client_id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.VARCHAR(length=20), nullable=True),
    sa.Column('time', sa.VARCHAR(length=20), nullable=True),
    sa.Column('service', sa.VARCHAR(length=100), nullable=True),
    sa.Column('comment', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
